table Pedidos
	lineageTag: 1b1e0334-db96-42ef-b433-2d2fe4a711db

	column 'ID Pedido'
		dataType: string
		lineageTag: fa4cc197-36f1-4a71-96be-8a4dbd8fb8e7
		summarizeBy: none
		sourceColumn: ID Pedido

		annotation SummarizationSetBy = Automatic

	column 'Data Pedido'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 752780f8-ddad-4ffb-9864-fc12b00408d5
		summarizeBy: none
		sourceColumn: Data Pedido

		variation Variation
			isDefault
			relationship: 417d3665-9263-481f-b4cd-6d557ac2cc69
			defaultHierarchy: LocalDateTable_9779925c-976d-4c75-9b63-9e67134b21ae.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data Envio'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0ec286ff-628f-4b55-a870-c92b173f93a2
		summarizeBy: none
		sourceColumn: Data Envio

		variation Variation
			isDefault
			relationship: bcb2b12a-a7b9-416a-a63a-1bea8e6ff76a
			defaultHierarchy: LocalDateTable_a6dedf35-2a25-41bb-8cac-228be9dc6bc5.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Modo Envio'
		dataType: string
		lineageTag: 95912d41-e44f-4ac2-bf2f-c9b057cf8a9e
		summarizeBy: none
		sourceColumn: Modo Envio

		annotation SummarizationSetBy = Automatic

	column 'Prioridade Pedido'
		dataType: string
		lineageTag: 3e1aa8f0-bdb9-45fd-ab80-1a5968b61d84
		summarizeBy: none
		sourceColumn: Prioridade Pedido

		annotation SummarizationSetBy = Automatic

	partition Pedidos = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\Pedro\Documents\Power_BI_DSA\lab03\1-datasets\Pedidos.csv"),[Delimiter=";", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ID Pedido", type text}, {"Data Pedido", type date}, {"Data Envio", type date}, {"Modo Envio", type text}, {"Prioridade Pedido", type text}}),
				    #"Texto Aparado" = Table.TransformColumns(#"Tipo Alterado",{{"ID Pedido", Text.Trim, type text}}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Texto Aparado")
				in
				    #"Duplicatas Removidas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

